// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6nXuqeueT6TPXw3WCxIrm1B0OUW7T8k8',
    appId: '1:237787119920:web:7bd91fe062bab8230448f5',
    messagingSenderId: '237787119920',
    projectId: 'eatprojekt',
    authDomain: 'eatprojekt.firebaseapp.com',
    storageBucket: 'eatprojekt.firebasestorage.app',
    measurementId: 'G-E576BV9NNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCP2wQJWp6Xr8QtaGo_4LZ2j5vNh_mqk',
    appId: '1:237787119920:android:609700fda76858120448f5',
    messagingSenderId: '237787119920',
    projectId: 'eatprojekt',
    storageBucket: 'eatprojekt.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-6iKkxdxoYCehop0v92mHd9g4YlQFqsM',
    appId: '1:237787119920:ios:969a40667928b3f20448f5',
    messagingSenderId: '237787119920',
    projectId: 'eatprojekt',
    storageBucket: 'eatprojekt.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-6iKkxdxoYCehop0v92mHd9g4YlQFqsM',
    appId: '1:237787119920:ios:969a40667928b3f20448f5',
    messagingSenderId: '237787119920',
    projectId: 'eatprojekt',
    storageBucket: 'eatprojekt.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6nXuqeueT6TPXw3WCxIrm1B0OUW7T8k8',
    appId: '1:237787119920:web:c8a29d14ede6ad3b0448f5',
    messagingSenderId: '237787119920',
    projectId: 'eatprojekt',
    authDomain: 'eatprojekt.firebaseapp.com',
    storageBucket: 'eatprojekt.firebasestorage.app',
    measurementId: 'G-DQYENY4BSX',
  );
}
