String localizeMealCategory(String? category) {
  return _categories[category] ?? category ?? 'Другое';
}

String localizeMealArea(String? area) {
  return _areas[area] ?? area ?? 'Не указано';
}

String localizeIngredient(String ingredient) {
  final key = ingredient.trim().toLowerCase();
  return _ingredients[key] ?? ingredient;
}

const _categories = {
  'Beef': 'Говядина',
  'Breakfast': 'Завтраки',
  'Chicken': 'Курица',
  'Dessert': 'Десерты',
  'Goat': 'Козлятина',
  'Lamb': 'Баранина',
  'Miscellaneous': 'Разное',
  'Pasta': 'Паста',
  'Pork': 'Свинина',
  'Seafood': 'Морепродукты',
  'Side': 'Гарниры',
  'Starter': 'Закуски',
  'Vegan': 'Веганские',
  'Vegetarian': 'Вегетарианские',
};

const _areas = {
  'American': 'Американская кухня',
  'British': 'Британская кухня',
  'Canadian': 'Канадская кухня',
  'Chinese': 'Китайская кухня',
  'Croatian': 'Хорватская кухня',
  'Dutch': 'Голландская кухня',
  'Egyptian': 'Египетская кухня',
  'Filipino': 'Филиппинская кухня',
  'French': 'Французская кухня',
  'Greek': 'Греческая кухня',
  'Indian': 'Индийская кухня',
  'Irish': 'Ирландская кухня',
  'Italian': 'Итальянская кухня',
  'Jamaican': 'Ямайская кухня',
  'Japanese': 'Японская кухня',
  'Kenyan': 'Кенийская кухня',
  'Malaysian': 'Малайзийская кухня',
  'Mexican': 'Мексиканская кухня',
  'Moroccan': 'Марокканская кухня',
  'Polish': 'Польская кухня',
  'Portuguese': 'Португальская кухня',
  'Russian': 'Русская кухня',
  'Spanish': 'Испанская кухня',
  'Thai': 'Тайская кухня',
  'Tunisian': 'Тунисская кухня',
  'Turkish': 'Турецкая кухня',
  'Ukrainian': 'Украинская кухня',
  'Unknown': 'Неизвестная кухня',
  'Vietnamese': 'Вьетнамская кухня',
};

const _ingredients = {
  'allspice': 'душистый перец',
  'almonds': 'миндаль',
  'apple cider vinegar': 'яблочный уксус',
  'apples': 'яблоки',
  'aubergine': 'баклажан',
  'avocado': 'авокадо',
  'baby plum tomatoes': 'маленькие сливовидные помидоры',
  'bacon': 'бекон',
  'baking powder': 'разрыхлитель',
  'balsamic vinegar': 'бальзамический уксус',
  'basil': 'базилик',
  'bay leaf': 'лавровый лист',
  'bay leaves': 'лавровые листья',
  'beef': 'говядина',
  'beef brisket': 'говяжья грудинка',
  'beef fillet': 'говяжье филе',
  'beef gravy': 'говяжья подлива',
  'beef stock': 'говяжий бульон',
  'beef mince': 'говяжий фарш',
  'black beans': 'черная фасоль',
  'black olives': 'черные оливки',
  'black pepper': 'черный перец',
  'boiling water': 'кипяток',
  'bread': 'хлеб',
  'breadcrumbs': 'панировочные сухари',
  'broccoli': 'брокколи',
  'brown sugar': 'коричневый сахар',
  'butter': 'сливочное масло',
  'cabbage': 'капуста',
  'cacao': 'какао',
  'carrots': 'морковь',
  'cashew nuts': 'кешью',
  'celery': 'сельдерей',
  'cheddar cheese': 'сыр чеддер',
  'cheese': 'сыр',
  'cherry tomatoes': 'помидоры черри',
  'chicken': 'курица',
  'chicken breast': 'куриная грудка',
  'chicken breasts': 'куриные грудки',
  'chicken legs': 'куриные ножки',
  'chicken stock': 'куриный бульон',
  'chicken thighs': 'куриные бедра',
  'chickpeas': 'нут',
  'chilli': 'чили',
  'chilli powder': 'порошок чили',
  'chopped tomatoes': 'нарезанные помидоры',
  'cinnamon': 'корица',
  'cloves': 'гвоздика',
  'cocoa': 'какао',
  'coconut cream': 'кокосовые сливки',
  'coconut milk': 'кокосовое молоко',
  'cod': 'треска',
  'coriander': 'кориандр',
  'corn flour': 'кукурузная мука',
  'courgettes': 'кабачки',
  'cream': 'сливки',
  'cream cheese': 'сливочный сыр',
  'cucumber': 'огурец',
  'cumin': 'кумин',
  'dark chocolate': 'темный шоколад',
  'dill': 'укроп',
  'doner meat': 'мясо для донера',
  'double cream': 'жирные сливки',
  'egg': 'яйцо',
  'eggs': 'яйца',
  'feta': 'фета',
  'fish': 'рыба',
  'fish sauce': 'рыбный соус',
  'flour': 'мука',
  'garlic': 'чеснок',
  'garlic clove': 'зубчик чеснока',
  'garlic cloves': 'зубчики чеснока',
  'ginger': 'имбирь',
  'goat meat': 'козлятина',
  'green beans': 'зеленая фасоль',
  'green chilli': 'зеленый чили',
  'green olives': 'зеленые оливки',
  'green pepper': 'зеленый перец',
  'ground almonds': 'молотый миндаль',
  'ground cumin': 'молотый кумин',
  'ham': 'ветчина',
  'honey': 'мед',
  'italian seasoning': 'итальянские травы',
  'kidney beans': 'красная фасоль',
  'lamb': 'баранина',
  'leek': 'лук-порей',
  'lemon': 'лимон',
  'lemon juice': 'лимонный сок',
  'lentils': 'чечевица',
  'lettuce': 'салат',
  'lime': 'лайм',
  'lime juice': 'сок лайма',
  'macaroni': 'макароны',
  'mayonnaise': 'майонез',
  'milk': 'молоко',
  'minced beef': 'говяжий фарш',
  'mint': 'мята',
  'mushrooms': 'грибы',
  'mustard': 'горчица',
  'nutmeg': 'мускатный орех',
  'oil': 'масло',
  'olive oil': 'оливковое масло',
  'onion': 'лук',
  'onions': 'лук',
  'orange': 'апельсин',
  'oregano': 'орегано',
  'paprika': 'паприка',
  'parmesan': 'пармезан',
  'parsley': 'петрушка',
  'pasta': 'паста',
  'peas': 'горошек',
  'pepper': 'перец',
  'plain flour': 'пшеничная мука',
  'pork': 'свинина',
  'potatoes': 'картофель',
  'potato': 'картофель',
  'red chilli': 'красный чили',
  'red onion': 'красный лук',
  'red pepper': 'красный перец',
  'rice': 'рис',
  'rocket': 'руккола',
  'rosemary': 'розмарин',
  'saffron': 'шафран',
  'salmon': 'лосось',
  'salt': 'соль',
  'sausages': 'сосиски',
  'sea salt': 'морская соль',
  'sesame seed': 'кунжут',
  'shallots': 'шалот',
  'shredded mexican cheese': 'тертый мексиканский сыр',
  'spinach': 'шпинат',
  'spring onions': 'зеленый лук',
  'sugar': 'сахар',
  'sunflower oil': 'подсолнечное масло',
  'sweetcorn': 'кукуруза',
  'thyme': 'тимьян',
  'tomato': 'помидор',
  'tomato ketchup': 'кетчуп',
  'tomato puree': 'томатная паста',
  'tomatoes': 'помидоры',
  'tuna': 'тунец',
  'turmeric': 'куркума',
  'vegetable oil': 'растительное масло',
  'vegetable stock': 'овощной бульон',
  'water': 'вода',
  'white wine': 'белое вино',
  'worcestershire sauce': 'вустерский соус',
  'yeast': 'дрожжи',
  'yogurt': 'йогурт',
};
